#-------------------------------------------------
# Makefile for kernel 2.6.x
#-------------------------------------------------

obj-y += nx_adc.o nx_alive.o nx_audio.o nx_clkpwr.o nx_csc.o nx_deinterlace.o nx_dma.o nx_dpc.o nx_ecid.o nx_gpio.o nx_i2c.o
obj-y += nx_idct.o nx_intc.o nx_mcud.o nx_mcus.o nx_mlc.o nx_mpegtsif.o nx_ohci.o nx_pwm.o nx_rotator.o nx_rtc.o nx_sdhc.o 
obj-y += nx_sspspi.o nx_timer.o nx_uart.o nx_vip.o
