/*
 * (C) Copyright 2010
 * jung hyun kim, Nexell Co, <jhkim@nexell.co.kr>
 *
 * See file CREDITS for list of people who contributed to this
 * project.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License as
 * published by the Free Software Foundation; either version 2 of
 * the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston,
 * MA 02111-1307 USA
 */
#include <linux/kernel.h>
#include <linux/module.h>
#include <linux/init.h>
#include <linux/types.h>
#include <asm/system_info.h>

/* nexell soc headers */
#include <mach/platform.h>
#include <mach/board_revisions.h>

/* debug macro */
#define DBGOUT(msg...)		{ printk(KERN_INFO msg); }

/*------------------------------------------------------------------------------
 * set nexell soc pad func.
 */
const U32 io_pad_lucy[NUMBER_OF_GPIO_MODULE][32] = {
	/* GPIO group A */
	{
	PAD_GPIOA00_LUCY, PAD_GPIOA01_LUCY, PAD_GPIOA02_LUCY, PAD_GPIOA03_LUCY,
	PAD_GPIOA04_LUCY, PAD_GPIOA05_LUCY, PAD_GPIOA06_LUCY, PAD_GPIOA07_LUCY,
	PAD_GPIOA08_LUCY, PAD_GPIOA09_LUCY, PAD_GPIOA10_LUCY, PAD_GPIOA11_LUCY,
	PAD_GPIOA12_LUCY, PAD_GPIOA13_LUCY, PAD_GPIOA14_LUCY, PAD_GPIOA15_LUCY,
	PAD_GPIOA16_LUCY, PAD_GPIOA17_LUCY, PAD_GPIOA18_LUCY, PAD_GPIOA19_LUCY,
	PAD_GPIOA20_LUCY, PAD_GPIOA21_LUCY, PAD_GPIOA22_LUCY, PAD_GPIOA23_LUCY,
	PAD_GPIOA24_LUCY, PAD_GPIOA25_LUCY, PAD_GPIOA26_LUCY, PAD_GPIOA27_LUCY,
	PAD_GPIOA28_LUCY, PAD_GPIOA29_LUCY, PAD_GPIOA30_LUCY, PAD_GPIOA31_LUCY,
	},
	/* GPIO group B */
	{
	PAD_GPIOB00_LUCY, PAD_GPIOB01_LUCY, PAD_GPIOB02_LUCY, PAD_GPIOB03_LUCY,
	PAD_GPIOB04_LUCY, PAD_GPIOB05_LUCY, PAD_GPIOB06_LUCY, PAD_GPIOB07_LUCY,
	PAD_GPIOB08_LUCY, PAD_GPIOB09_LUCY, PAD_GPIOB10_LUCY, PAD_GPIOB11_LUCY,
	PAD_GPIOB12_LUCY, PAD_GPIOB13_LUCY, PAD_GPIOB14_LUCY, PAD_GPIOB15_LUCY,
	PAD_GPIOB16_LUCY, PAD_GPIOB17_LUCY, PAD_GPIOB18_LUCY, PAD_GPIOB19_LUCY,
	PAD_GPIOB20_LUCY, PAD_GPIOB21_LUCY, PAD_GPIOB22_LUCY, PAD_GPIOB23_LUCY,
	PAD_GPIOB24_LUCY, PAD_GPIOB25_LUCY, PAD_GPIOB26_LUCY, PAD_GPIOB27_LUCY,
	PAD_GPIOB28_LUCY, PAD_GPIOB29_LUCY, PAD_GPIOB30_LUCY, PAD_GPIOB31_LUCY,
	},
	/* GPIO group C */
	{
	PAD_GPIOC00_LUCY, PAD_GPIOC01_LUCY, PAD_GPIOC02_LUCY, PAD_GPIOC03_LUCY,
	PAD_GPIOC04_LUCY, PAD_GPIOC05_LUCY, PAD_GPIOC06_LUCY, PAD_GPIOC07_LUCY,
	PAD_GPIOC08_LUCY, PAD_GPIOC09_LUCY, PAD_GPIOC10_LUCY, PAD_GPIOC11_LUCY,
	PAD_GPIOC12_LUCY, PAD_GPIOC13_LUCY, PAD_GPIOC14_LUCY, PAD_GPIOC15_LUCY,
	PAD_GPIOC16_LUCY, PAD_GPIOC17_LUCY, PAD_GPIOC18_LUCY, PAD_GPIOC19_LUCY,
	PAD_GPIOC20_LUCY, PAD_GPIOC21_LUCY, PAD_GPIOC22_LUCY, PAD_GPIOC23_LUCY,
	PAD_GPIOC24_LUCY, PAD_GPIOC25_LUCY, PAD_GPIOC26_LUCY, PAD_GPIOC27_LUCY,
	PAD_GPIOC28_LUCY, PAD_GPIOC29_LUCY, PAD_GPIOC30_LUCY, PAD_GPIOC31_LUCY,
	},
	/* GPIO group D */
	{
	PAD_GPIOD00_LUCY, PAD_GPIOD01_LUCY, PAD_GPIOD02_LUCY, PAD_GPIOD03_LUCY,
	PAD_GPIOD04_LUCY, PAD_GPIOD05_LUCY, PAD_GPIOD06_LUCY, PAD_GPIOD07_LUCY,
	PAD_GPIOD08_LUCY, PAD_GPIOD09_LUCY, PAD_GPIOD10_LUCY, PAD_GPIOD11_LUCY,
	PAD_GPIOD12_LUCY, PAD_GPIOD13_LUCY, PAD_GPIOD14_LUCY, PAD_GPIOD15_LUCY,
	PAD_GPIOD16_LUCY, PAD_GPIOD17_LUCY, PAD_GPIOD18_LUCY, PAD_GPIOD19_LUCY,
	PAD_GPIOD20_LUCY, PAD_GPIOD21_LUCY, PAD_GPIOD22_LUCY, PAD_GPIOD23_LUCY,
	PAD_GPIOD24_LUCY, 0,                0,                0,
	0,                0,                0,                0,
	}
};

const U32 io_pad_rio[NUMBER_OF_GPIO_MODULE][32] = {
	/* GPIO group A */
	{
	PAD_GPIOA00_RIO, PAD_GPIOA01_RIO, PAD_GPIOA02_RIO, PAD_GPIOA03_RIO,
	PAD_GPIOA04_RIO, PAD_GPIOA05_RIO, PAD_GPIOA06_RIO, PAD_GPIOA07_RIO,
	PAD_GPIOA08_RIO, PAD_GPIOA09_RIO, PAD_GPIOA10_RIO, PAD_GPIOA11_RIO,
	PAD_GPIOA12_RIO, PAD_GPIOA13_RIO, PAD_GPIOA14_RIO, PAD_GPIOA15_RIO,
	PAD_GPIOA16_RIO, PAD_GPIOA17_RIO, PAD_GPIOA18_RIO, PAD_GPIOA19_RIO,
	PAD_GPIOA20_RIO, PAD_GPIOA21_RIO, PAD_GPIOA22_RIO, PAD_GPIOA23_RIO,
	PAD_GPIOA24_RIO, PAD_GPIOA25_RIO, PAD_GPIOA26_RIO, PAD_GPIOA27_RIO,
	PAD_GPIOA28_RIO, PAD_GPIOA29_RIO, PAD_GPIOA30_RIO, PAD_GPIOA31_RIO,
	},
	/* GPIO group B */
	{
	PAD_GPIOB00_RIO, PAD_GPIOB01_RIO, PAD_GPIOB02_RIO, PAD_GPIOB03_RIO,
	PAD_GPIOB04_RIO, PAD_GPIOB05_RIO, PAD_GPIOB06_RIO, PAD_GPIOB07_RIO,
	PAD_GPIOB08_RIO, PAD_GPIOB09_RIO, PAD_GPIOB10_RIO, PAD_GPIOB11_RIO,
	PAD_GPIOB12_RIO, PAD_GPIOB13_RIO, PAD_GPIOB14_RIO, PAD_GPIOB15_RIO,
	PAD_GPIOB16_RIO, PAD_GPIOB17_RIO, PAD_GPIOB18_RIO, PAD_GPIOB19_RIO,
	PAD_GPIOB20_RIO, PAD_GPIOB21_RIO, PAD_GPIOB22_RIO, PAD_GPIOB23_RIO,
	PAD_GPIOB24_RIO, PAD_GPIOB25_RIO, PAD_GPIOB26_RIO, PAD_GPIOB27_RIO,
	PAD_GPIOB28_RIO, PAD_GPIOB29_RIO, PAD_GPIOB30_RIO, PAD_GPIOB31_RIO,
	},
	/* GPIO group C */
	{
	PAD_GPIOC00_RIO, PAD_GPIOC01_RIO, PAD_GPIOC02_RIO, PAD_GPIOC03_RIO,
	PAD_GPIOC04_RIO, PAD_GPIOC05_RIO, PAD_GPIOC06_RIO, PAD_GPIOC07_RIO,
	PAD_GPIOC08_RIO, PAD_GPIOC09_RIO, PAD_GPIOC10_RIO, PAD_GPIOC11_RIO,
	PAD_GPIOC12_RIO, PAD_GPIOC13_RIO, PAD_GPIOC14_RIO, PAD_GPIOC15_RIO,
	PAD_GPIOC16_RIO, PAD_GPIOC17_RIO, PAD_GPIOC18_RIO, PAD_GPIOC19_RIO,
	PAD_GPIOC20_RIO, PAD_GPIOC21_RIO, PAD_GPIOC22_RIO, PAD_GPIOC23_RIO,
	PAD_GPIOC24_RIO, PAD_GPIOC25_RIO, PAD_GPIOC26_RIO, PAD_GPIOC27_RIO,
	PAD_GPIOC28_RIO, PAD_GPIOC29_RIO, PAD_GPIOC30_RIO, PAD_GPIOC31_RIO,
	},
	/* GPIO group D */
	{
	PAD_GPIOD00_RIO, PAD_GPIOD01_RIO, PAD_GPIOD02_RIO, PAD_GPIOD03_RIO,
	PAD_GPIOD04_RIO, PAD_GPIOD05_RIO, PAD_GPIOD06_RIO, PAD_GPIOD07_RIO,
	PAD_GPIOD08_RIO, PAD_GPIOD09_RIO, PAD_GPIOD10_RIO, PAD_GPIOD11_RIO,
	PAD_GPIOD12_RIO, PAD_GPIOD13_RIO, PAD_GPIOD14_RIO, PAD_GPIOD15_RIO,
	PAD_GPIOD16_RIO, PAD_GPIOD17_RIO, PAD_GPIOD18_RIO, PAD_GPIOD19_RIO,
	PAD_GPIOD20_RIO, PAD_GPIOD21_RIO, PAD_GPIOD22_RIO, PAD_GPIOD23_RIO,
	PAD_GPIOD24_RIO, 0,                0,                0,
	0,                   0,                0,                0,
	}
};

const U32 io_pad_rio_beta[NUMBER_OF_GPIO_MODULE][32] = {
	/* GPIO group A */
	{
	PAD_GPIOA00_RIO_BETA, PAD_GPIOA01_RIO_BETA, PAD_GPIOA02_RIO_BETA, PAD_GPIOA03_RIO_BETA,
	PAD_GPIOA04_RIO_BETA, PAD_GPIOA05_RIO_BETA, PAD_GPIOA06_RIO_BETA, PAD_GPIOA07_RIO_BETA,
	PAD_GPIOA08_RIO_BETA, PAD_GPIOA09_RIO_BETA, PAD_GPIOA10_RIO_BETA, PAD_GPIOA11_RIO_BETA,
	PAD_GPIOA12_RIO_BETA, PAD_GPIOA13_RIO_BETA, PAD_GPIOA14_RIO_BETA, PAD_GPIOA15_RIO_BETA,
	PAD_GPIOA16_RIO_BETA, PAD_GPIOA17_RIO_BETA, PAD_GPIOA18_RIO_BETA, PAD_GPIOA19_RIO_BETA,
	PAD_GPIOA20_RIO_BETA, PAD_GPIOA21_RIO_BETA, PAD_GPIOA22_RIO_BETA, PAD_GPIOA23_RIO_BETA,
	PAD_GPIOA24_RIO_BETA, PAD_GPIOA25_RIO_BETA, PAD_GPIOA26_RIO_BETA, PAD_GPIOA27_RIO_BETA,
	PAD_GPIOA28_RIO_BETA, PAD_GPIOA29_RIO_BETA, PAD_GPIOA30_RIO_BETA, PAD_GPIOA31_RIO_BETA,
	},
	/* GPIO group B */
	{
	PAD_GPIOB00_RIO_BETA, PAD_GPIOB01_RIO_BETA, PAD_GPIOB02_RIO_BETA, PAD_GPIOB03_RIO_BETA,
	PAD_GPIOB04_RIO_BETA, PAD_GPIOB05_RIO_BETA, PAD_GPIOB06_RIO_BETA, PAD_GPIOB07_RIO_BETA,
	PAD_GPIOB08_RIO_BETA, PAD_GPIOB09_RIO_BETA, PAD_GPIOB10_RIO_BETA, PAD_GPIOB11_RIO_BETA,
	PAD_GPIOB12_RIO_BETA, PAD_GPIOB13_RIO_BETA, PAD_GPIOB14_RIO_BETA, PAD_GPIOB15_RIO_BETA,
	PAD_GPIOB16_RIO_BETA, PAD_GPIOB17_RIO_BETA, PAD_GPIOB18_RIO_BETA, PAD_GPIOB19_RIO_BETA,
	PAD_GPIOB20_RIO_BETA, PAD_GPIOB21_RIO_BETA, PAD_GPIOB22_RIO_BETA, PAD_GPIOB23_RIO_BETA,
	PAD_GPIOB24_RIO_BETA, PAD_GPIOB25_RIO_BETA, PAD_GPIOB26_RIO_BETA, PAD_GPIOB27_RIO_BETA,
	PAD_GPIOB28_RIO_BETA, PAD_GPIOB29_RIO_BETA, PAD_GPIOB30_RIO_BETA, PAD_GPIOB31_RIO_BETA,
	},
	/* GPIO group C */
	{
	PAD_GPIOC00_RIO_BETA, PAD_GPIOC01_RIO_BETA, PAD_GPIOC02_RIO_BETA, PAD_GPIOC03_RIO_BETA,
	PAD_GPIOC04_RIO_BETA, PAD_GPIOC05_RIO_BETA, PAD_GPIOC06_RIO_BETA, PAD_GPIOC07_RIO_BETA,
	PAD_GPIOC08_RIO_BETA, PAD_GPIOC09_RIO_BETA, PAD_GPIOC10_RIO_BETA, PAD_GPIOC11_RIO_BETA,
	PAD_GPIOC12_RIO_BETA, PAD_GPIOC13_RIO_BETA, PAD_GPIOC14_RIO_BETA, PAD_GPIOC15_RIO_BETA,
	PAD_GPIOC16_RIO_BETA, PAD_GPIOC17_RIO_BETA, PAD_GPIOC18_RIO_BETA, PAD_GPIOC19_RIO_BETA,
	PAD_GPIOC20_RIO_BETA, PAD_GPIOC21_RIO_BETA, PAD_GPIOC22_RIO_BETA, PAD_GPIOC23_RIO_BETA,
	PAD_GPIOC24_RIO_BETA, PAD_GPIOC25_RIO_BETA, PAD_GPIOC26_RIO_BETA, PAD_GPIOC27_RIO_BETA,
	PAD_GPIOC28_RIO_BETA, PAD_GPIOC29_RIO_BETA, PAD_GPIOC30_RIO_BETA, PAD_GPIOC31_RIO_BETA,
	},
	/* GPIO group D */
	{
	PAD_GPIOD00_RIO_BETA, PAD_GPIOD01_RIO_BETA, PAD_GPIOD02_RIO_BETA, PAD_GPIOD03_RIO_BETA,
	PAD_GPIOD04_RIO_BETA, PAD_GPIOD05_RIO_BETA, PAD_GPIOD06_RIO_BETA, PAD_GPIOD07_RIO_BETA,
	PAD_GPIOD08_RIO_BETA, PAD_GPIOD09_RIO_BETA, PAD_GPIOD10_RIO_BETA, PAD_GPIOD11_RIO_BETA,
	PAD_GPIOD12_RIO_BETA, PAD_GPIOD13_RIO_BETA, PAD_GPIOD14_RIO_BETA, PAD_GPIOD15_RIO_BETA,
	PAD_GPIOD16_RIO_BETA, PAD_GPIOD17_RIO_BETA, PAD_GPIOD18_RIO_BETA, PAD_GPIOD19_RIO_BETA,
	PAD_GPIOD20_RIO_BETA, PAD_GPIOD21_RIO_BETA, PAD_GPIOD22_RIO_BETA, PAD_GPIOD23_RIO_BETA,
	PAD_GPIOD24_RIO_BETA, 0,                    0,                    0,
	0,                    0,                    0,                    0,
	}
};

const U32 io_pad_rio_ep[NUMBER_OF_GPIO_MODULE][32] = {
	/* GPIO group A */
	{
	PAD_GPIOA00_RIO_EP, PAD_GPIOA01_RIO_EP, PAD_GPIOA02_RIO_EP, PAD_GPIOA03_RIO_EP,
	PAD_GPIOA04_RIO_EP, PAD_GPIOA05_RIO_EP, PAD_GPIOA06_RIO_EP, PAD_GPIOA07_RIO_EP,
	PAD_GPIOA08_RIO_EP, PAD_GPIOA09_RIO_EP, PAD_GPIOA10_RIO_EP, PAD_GPIOA11_RIO_EP,
	PAD_GPIOA12_RIO_EP, PAD_GPIOA13_RIO_EP, PAD_GPIOA14_RIO_EP, PAD_GPIOA15_RIO_EP,
	PAD_GPIOA16_RIO_EP, PAD_GPIOA17_RIO_EP, PAD_GPIOA18_RIO_EP, PAD_GPIOA19_RIO_EP,
	PAD_GPIOA20_RIO_EP, PAD_GPIOA21_RIO_EP, PAD_GPIOA22_RIO_EP, PAD_GPIOA23_RIO_EP,
	PAD_GPIOA24_RIO_EP, PAD_GPIOA25_RIO_EP, PAD_GPIOA26_RIO_EP, PAD_GPIOA27_RIO_EP,
	PAD_GPIOA28_RIO_EP, PAD_GPIOA29_RIO_EP, PAD_GPIOA30_RIO_EP, PAD_GPIOA31_RIO_EP,
	},
	/* GPIO group B */
	{
	PAD_GPIOB00_RIO_EP, PAD_GPIOB01_RIO_EP, PAD_GPIOB02_RIO_EP, PAD_GPIOB03_RIO_EP,
	PAD_GPIOB04_RIO_EP, PAD_GPIOB05_RIO_EP, PAD_GPIOB06_RIO_EP, PAD_GPIOB07_RIO_EP,
	PAD_GPIOB08_RIO_EP, PAD_GPIOB09_RIO_EP, PAD_GPIOB10_RIO_EP, PAD_GPIOB11_RIO_EP,
	PAD_GPIOB12_RIO_EP, PAD_GPIOB13_RIO_EP, PAD_GPIOB14_RIO_EP, PAD_GPIOB15_RIO_EP,
	PAD_GPIOB16_RIO_EP, PAD_GPIOB17_RIO_EP, PAD_GPIOB18_RIO_EP, PAD_GPIOB19_RIO_EP,
	PAD_GPIOB20_RIO_EP, PAD_GPIOB21_RIO_EP, PAD_GPIOB22_RIO_EP, PAD_GPIOB23_RIO_EP,
	PAD_GPIOB24_RIO_EP, PAD_GPIOB25_RIO_EP, PAD_GPIOB26_RIO_EP, PAD_GPIOB27_RIO_EP,
	PAD_GPIOB28_RIO_EP, PAD_GPIOB29_RIO_EP, PAD_GPIOB30_RIO_EP, PAD_GPIOB31_RIO_EP,
	},
	/* GPIO group C */
	{
	PAD_GPIOC00_RIO_EP, PAD_GPIOC01_RIO_EP, PAD_GPIOC02_RIO_EP, PAD_GPIOC03_RIO_EP,
	PAD_GPIOC04_RIO_EP, PAD_GPIOC05_RIO_EP, PAD_GPIOC06_RIO_EP, PAD_GPIOC07_RIO_EP,
	PAD_GPIOC08_RIO_EP, PAD_GPIOC09_RIO_EP, PAD_GPIOC10_RIO_EP, PAD_GPIOC11_RIO_EP,
	PAD_GPIOC12_RIO_EP, PAD_GPIOC13_RIO_EP, PAD_GPIOC14_RIO_EP, PAD_GPIOC15_RIO_EP,
	PAD_GPIOC16_RIO_EP, PAD_GPIOC17_RIO_EP, PAD_GPIOC18_RIO_EP, PAD_GPIOC19_RIO_EP,
	PAD_GPIOC20_RIO_EP, PAD_GPIOC21_RIO_EP, PAD_GPIOC22_RIO_EP, PAD_GPIOC23_RIO_EP,
	PAD_GPIOC24_RIO_EP, PAD_GPIOC25_RIO_EP, PAD_GPIOC26_RIO_EP, PAD_GPIOC27_RIO_EP,
	PAD_GPIOC28_RIO_EP, PAD_GPIOC29_RIO_EP, PAD_GPIOC30_RIO_EP, PAD_GPIOC31_RIO_EP,
	},
	/* GPIO group D */
	{
	PAD_GPIOD00_RIO_EP, PAD_GPIOD01_RIO_EP, PAD_GPIOD02_RIO_EP, PAD_GPIOD03_RIO_EP,
	PAD_GPIOD04_RIO_EP, PAD_GPIOD05_RIO_EP, PAD_GPIOD06_RIO_EP, PAD_GPIOD07_RIO_EP,
	PAD_GPIOD08_RIO_EP, PAD_GPIOD09_RIO_EP, PAD_GPIOD10_RIO_EP, PAD_GPIOD11_RIO_EP,
	PAD_GPIOD12_RIO_EP, PAD_GPIOD13_RIO_EP, PAD_GPIOD14_RIO_EP, PAD_GPIOD15_RIO_EP,
	PAD_GPIOD16_RIO_EP, PAD_GPIOD17_RIO_EP, PAD_GPIOD18_RIO_EP, PAD_GPIOD19_RIO_EP,
	PAD_GPIOD20_RIO_EP, PAD_GPIOD21_RIO_EP, PAD_GPIOD22_RIO_EP, PAD_GPIOD23_RIO_EP,
	PAD_GPIOD24_RIO_EP, 0,                  0,                  0,
	0,                  0,                  0,                  0,
	}
};

const U32 io_pad_val[NUMBER_OF_GPIO_MODULE][32] = {
	/* GPIO group A */
	{
	PAD_GPIOA00_VAL, PAD_GPIOA01_VAL, PAD_GPIOA02_VAL, PAD_GPIOA03_VAL,
	PAD_GPIOA04_VAL, PAD_GPIOA05_VAL, PAD_GPIOA06_VAL, PAD_GPIOA07_VAL,
	PAD_GPIOA08_VAL, PAD_GPIOA09_VAL, PAD_GPIOA10_VAL, PAD_GPIOA11_VAL,
	PAD_GPIOA12_VAL, PAD_GPIOA13_VAL, PAD_GPIOA14_VAL, PAD_GPIOA15_VAL,
	PAD_GPIOA16_VAL, PAD_GPIOA17_VAL, PAD_GPIOA18_VAL, PAD_GPIOA19_VAL,
	PAD_GPIOA20_VAL, PAD_GPIOA21_VAL, PAD_GPIOA22_VAL, PAD_GPIOA23_VAL,
	PAD_GPIOA24_VAL, PAD_GPIOA25_VAL, PAD_GPIOA26_VAL, PAD_GPIOA27_VAL,
	PAD_GPIOA28_VAL, PAD_GPIOA29_VAL, PAD_GPIOA30_VAL, PAD_GPIOA31_VAL,
	},
	/* GPIO group B */
	{
	PAD_GPIOB00_VAL, PAD_GPIOB01_VAL, PAD_GPIOB02_VAL, PAD_GPIOB03_VAL,
	PAD_GPIOB04_VAL, PAD_GPIOB05_VAL, PAD_GPIOB06_VAL, PAD_GPIOB07_VAL,
	PAD_GPIOB08_VAL, PAD_GPIOB09_VAL, PAD_GPIOB10_VAL, PAD_GPIOB11_VAL,
	PAD_GPIOB12_VAL, PAD_GPIOB13_VAL, PAD_GPIOB14_VAL, PAD_GPIOB15_VAL,
	PAD_GPIOB16_VAL, PAD_GPIOB17_VAL, PAD_GPIOB18_VAL, PAD_GPIOB19_VAL,
	PAD_GPIOB20_VAL, PAD_GPIOB21_VAL, PAD_GPIOB22_VAL, PAD_GPIOB23_VAL,
	PAD_GPIOB24_VAL, PAD_GPIOB25_VAL, PAD_GPIOB26_VAL, PAD_GPIOB27_VAL,
	PAD_GPIOB28_VAL, PAD_GPIOB29_VAL, PAD_GPIOB30_VAL, PAD_GPIOB31_VAL,
	},
	/* GPIO group C */
	{
	PAD_GPIOC00_VAL, PAD_GPIOC01_VAL, PAD_GPIOC02_VAL, PAD_GPIOC03_VAL,
	PAD_GPIOC04_VAL, PAD_GPIOC05_VAL, PAD_GPIOC06_VAL, PAD_GPIOC07_VAL,
	PAD_GPIOC08_VAL, PAD_GPIOC09_VAL, PAD_GPIOC10_VAL, PAD_GPIOC11_VAL,
	PAD_GPIOC12_VAL, PAD_GPIOC13_VAL, PAD_GPIOC14_VAL, PAD_GPIOC15_VAL,
	PAD_GPIOC16_VAL, PAD_GPIOC17_VAL, PAD_GPIOC18_VAL, PAD_GPIOC19_VAL,
	PAD_GPIOC20_VAL, PAD_GPIOC21_VAL, PAD_GPIOC22_VAL, PAD_GPIOC23_VAL,
	PAD_GPIOC24_VAL, PAD_GPIOC25_VAL, PAD_GPIOC26_VAL, PAD_GPIOC27_VAL,
	PAD_GPIOC28_VAL, PAD_GPIOC29_VAL, PAD_GPIOC30_VAL, PAD_GPIOC31_VAL,
	},
	/* GPIO group D */
	{
	PAD_GPIOD00_VAL, PAD_GPIOD01_VAL, PAD_GPIOD02_VAL, PAD_GPIOD03_VAL,
	PAD_GPIOD04_VAL, PAD_GPIOD05_VAL, PAD_GPIOD06_VAL, PAD_GPIOD07_VAL,
	PAD_GPIOD08_VAL, PAD_GPIOD09_VAL, PAD_GPIOD10_VAL, PAD_GPIOD11_VAL,
	PAD_GPIOD12_VAL, PAD_GPIOD13_VAL, PAD_GPIOD14_VAL, PAD_GPIOD15_VAL,
	PAD_GPIOD16_VAL, PAD_GPIOD17_VAL, PAD_GPIOD18_VAL, PAD_GPIOD19_VAL,
	PAD_GPIOD20_VAL, PAD_GPIOD21_VAL, PAD_GPIOD22_VAL, PAD_GPIOD23_VAL,
	PAD_GPIOD24_VAL, 0,                0,                0,
	0,               0,                0,                0,
	}
};

const U32 io_pad_val_cip[NUMBER_OF_GPIO_MODULE][32] = {
	/* GPIO group A */
	{
	PAD_GPIOA00_VAL_CIP, PAD_GPIOA01_VAL_CIP, PAD_GPIOA02_VAL_CIP, PAD_GPIOA03_VAL_CIP,
	PAD_GPIOA04_VAL_CIP, PAD_GPIOA05_VAL_CIP, PAD_GPIOA06_VAL_CIP, PAD_GPIOA07_VAL_CIP,
	PAD_GPIOA08_VAL_CIP, PAD_GPIOA09_VAL_CIP, PAD_GPIOA10_VAL_CIP, PAD_GPIOA11_VAL_CIP,
	PAD_GPIOA12_VAL_CIP, PAD_GPIOA13_VAL_CIP, PAD_GPIOA14_VAL_CIP, PAD_GPIOA15_VAL_CIP,
	PAD_GPIOA16_VAL_CIP, PAD_GPIOA17_VAL_CIP, PAD_GPIOA18_VAL_CIP, PAD_GPIOA19_VAL_CIP,
	PAD_GPIOA20_VAL_CIP, PAD_GPIOA21_VAL_CIP, PAD_GPIOA22_VAL_CIP, PAD_GPIOA23_VAL_CIP,
	PAD_GPIOA24_VAL_CIP, PAD_GPIOA25_VAL_CIP, PAD_GPIOA26_VAL_CIP, PAD_GPIOA27_VAL_CIP,
	PAD_GPIOA28_VAL_CIP, PAD_GPIOA29_VAL_CIP, PAD_GPIOA30_VAL_CIP, PAD_GPIOA31_VAL_CIP,
	},
	/* GPIO group B */
	{
	PAD_GPIOB00_VAL_CIP, PAD_GPIOB01_VAL_CIP, PAD_GPIOB02_VAL_CIP, PAD_GPIOB03_VAL_CIP,
	PAD_GPIOB04_VAL_CIP, PAD_GPIOB05_VAL_CIP, PAD_GPIOB06_VAL_CIP, PAD_GPIOB07_VAL_CIP,
	PAD_GPIOB08_VAL_CIP, PAD_GPIOB09_VAL_CIP, PAD_GPIOB10_VAL_CIP, PAD_GPIOB11_VAL_CIP,
	PAD_GPIOB12_VAL_CIP, PAD_GPIOB13_VAL_CIP, PAD_GPIOB14_VAL_CIP, PAD_GPIOB15_VAL_CIP,
	PAD_GPIOB16_VAL_CIP, PAD_GPIOB17_VAL_CIP, PAD_GPIOB18_VAL_CIP, PAD_GPIOB19_VAL_CIP,
	PAD_GPIOB20_VAL_CIP, PAD_GPIOB21_VAL_CIP, PAD_GPIOB22_VAL_CIP, PAD_GPIOB23_VAL_CIP,
	PAD_GPIOB24_VAL_CIP, PAD_GPIOB25_VAL_CIP, PAD_GPIOB26_VAL_CIP, PAD_GPIOB27_VAL_CIP,
	PAD_GPIOB28_VAL_CIP, PAD_GPIOB29_VAL_CIP, PAD_GPIOB30_VAL_CIP, PAD_GPIOB31_VAL_CIP,
	},
	/* GPIO group C */
	{
	PAD_GPIOC00_VAL_CIP, PAD_GPIOC01_VAL_CIP, PAD_GPIOC02_VAL_CIP, PAD_GPIOC03_VAL_CIP,
	PAD_GPIOC04_VAL_CIP, PAD_GPIOC05_VAL_CIP, PAD_GPIOC06_VAL_CIP, PAD_GPIOC07_VAL_CIP,
	PAD_GPIOC08_VAL_CIP, PAD_GPIOC09_VAL_CIP, PAD_GPIOC10_VAL_CIP, PAD_GPIOC11_VAL_CIP,
	PAD_GPIOC12_VAL_CIP, PAD_GPIOC13_VAL_CIP, PAD_GPIOC14_VAL_CIP, PAD_GPIOC15_VAL_CIP,
	PAD_GPIOC16_VAL_CIP, PAD_GPIOC17_VAL_CIP, PAD_GPIOC18_VAL_CIP, PAD_GPIOC19_VAL_CIP,
	PAD_GPIOC20_VAL_CIP, PAD_GPIOC21_VAL_CIP, PAD_GPIOC22_VAL_CIP, PAD_GPIOC23_VAL_CIP,
	PAD_GPIOC24_VAL_CIP, PAD_GPIOC25_VAL_CIP, PAD_GPIOC26_VAL_CIP, PAD_GPIOC27_VAL_CIP,
	PAD_GPIOC28_VAL_CIP, PAD_GPIOC29_VAL_CIP, PAD_GPIOC30_VAL_CIP, PAD_GPIOC31_VAL_CIP,
	},
	/* GPIO group D */
	{
	PAD_GPIOD00_VAL_CIP, PAD_GPIOD01_VAL_CIP, PAD_GPIOD02_VAL_CIP, PAD_GPIOD03_VAL_CIP,
	PAD_GPIOD04_VAL_CIP, PAD_GPIOD05_VAL_CIP, PAD_GPIOD06_VAL_CIP, PAD_GPIOD07_VAL_CIP,
	PAD_GPIOD08_VAL_CIP, PAD_GPIOD09_VAL_CIP, PAD_GPIOD10_VAL_CIP, PAD_GPIOD11_VAL_CIP,
	PAD_GPIOD12_VAL_CIP, PAD_GPIOD13_VAL_CIP, PAD_GPIOD14_VAL_CIP, PAD_GPIOD15_VAL_CIP,
	PAD_GPIOD16_VAL_CIP, PAD_GPIOD17_VAL_CIP, PAD_GPIOD18_VAL_CIP, PAD_GPIOD19_VAL_CIP,
	PAD_GPIOD20_VAL_CIP, PAD_GPIOD21_VAL_CIP, PAD_GPIOD22_VAL_CIP, PAD_GPIOD23_VAL_CIP,
	PAD_GPIOD24_VAL_CIP, 0,			  0,		       0,
	0,                   0,			  0,		       0,
	}
};

const U32 io_pad_vtk[NUMBER_OF_GPIO_MODULE][32] = {
	/* GPIO group A */
	{
	PAD_GPIOA00_VTK, PAD_GPIOA01_VTK, PAD_GPIOA02_VTK, PAD_GPIOA03_VTK,
	PAD_GPIOA04_VTK, PAD_GPIOA05_VTK, PAD_GPIOA06_VTK, PAD_GPIOA07_VTK,
	PAD_GPIOA08_VTK, PAD_GPIOA09_VTK, PAD_GPIOA10_VTK, PAD_GPIOA11_VTK,
	PAD_GPIOA12_VTK, PAD_GPIOA13_VTK, PAD_GPIOA14_VTK, PAD_GPIOA15_VTK,
	PAD_GPIOA16_VTK, PAD_GPIOA17_VTK, PAD_GPIOA18_VTK, PAD_GPIOA19_VTK,
	PAD_GPIOA20_VTK, PAD_GPIOA21_VTK, PAD_GPIOA22_VTK, PAD_GPIOA23_VTK,
	PAD_GPIOA24_VTK, PAD_GPIOA25_VTK, PAD_GPIOA26_VTK, PAD_GPIOA27_VTK,
	PAD_GPIOA28_VTK, PAD_GPIOA29_VTK, PAD_GPIOA30_VTK, PAD_GPIOA31_VTK,
	},
	/* GPIO group B */
	{
	PAD_GPIOB00_VTK, PAD_GPIOB01_VTK, PAD_GPIOB02_VTK, PAD_GPIOB03_VTK,
	PAD_GPIOB04_VTK, PAD_GPIOB05_VTK, PAD_GPIOB06_VTK, PAD_GPIOB07_VTK,
	PAD_GPIOB08_VTK, PAD_GPIOB09_VTK, PAD_GPIOB10_VTK, PAD_GPIOB11_VTK,
	PAD_GPIOB12_VTK, PAD_GPIOB13_VTK, PAD_GPIOB14_VTK, PAD_GPIOB15_VTK,
	PAD_GPIOB16_VTK, PAD_GPIOB17_VTK, PAD_GPIOB18_VTK, PAD_GPIOB19_VTK,
	PAD_GPIOB20_VTK, PAD_GPIOB21_VTK, PAD_GPIOB22_VTK, PAD_GPIOB23_VTK,
	PAD_GPIOB24_VTK, PAD_GPIOB25_VTK, PAD_GPIOB26_VTK, PAD_GPIOB27_VTK,
	PAD_GPIOB28_VTK, PAD_GPIOB29_VTK, PAD_GPIOB30_VTK, PAD_GPIOB31_VTK,
	},
	/* GPIO group C */
	{
	PAD_GPIOC00_VTK, PAD_GPIOC01_VTK, PAD_GPIOC02_VTK, PAD_GPIOC03_VTK,
	PAD_GPIOC04_VTK, PAD_GPIOC05_VTK, PAD_GPIOC06_VTK, PAD_GPIOC07_VTK,
	PAD_GPIOC08_VTK, PAD_GPIOC09_VTK, PAD_GPIOC10_VTK, PAD_GPIOC11_VTK,
	PAD_GPIOC12_VTK, PAD_GPIOC13_VTK, PAD_GPIOC14_VTK, PAD_GPIOC15_VTK,
	PAD_GPIOC16_VTK, PAD_GPIOC17_VTK, PAD_GPIOC18_VTK, PAD_GPIOC19_VTK,
	PAD_GPIOC20_VTK, PAD_GPIOC21_VTK, PAD_GPIOC22_VTK, PAD_GPIOC23_VTK,
	PAD_GPIOC24_VTK, PAD_GPIOC25_VTK, PAD_GPIOC26_VTK, PAD_GPIOC27_VTK,
	PAD_GPIOC28_VTK, PAD_GPIOC29_VTK, PAD_GPIOC30_VTK, PAD_GPIOC31_VTK,
	},
	/* GPIO group D */
	{
	PAD_GPIOD00_VTK, PAD_GPIOD01_VTK, PAD_GPIOD02_VTK, PAD_GPIOD03_VTK,
	PAD_GPIOD04_VTK, PAD_GPIOD05_VTK, PAD_GPIOD06_VTK, PAD_GPIOD07_VTK,
	PAD_GPIOD08_VTK, PAD_GPIOD09_VTK, PAD_GPIOD10_VTK, PAD_GPIOD11_VTK,
	PAD_GPIOD12_VTK, PAD_GPIOD13_VTK, PAD_GPIOD14_VTK, PAD_GPIOD15_VTK,
	PAD_GPIOD16_VTK, PAD_GPIOD17_VTK, PAD_GPIOD18_VTK, PAD_GPIOD19_VTK,
	PAD_GPIOD20_VTK, PAD_GPIOD21_VTK, PAD_GPIOD22_VTK, PAD_GPIOD23_VTK,
	PAD_GPIOD24_VTK, 0,                0,                0,
	0,               0,                0,                0,
	}
};

static void init_gpio_pad(void)
{
	int  io_grp, io_bit;
	U32  io_mod, outval, detect, pullup, strength;

	const U32 (*p_io_pad)[NUMBER_OF_GPIO_MODULE][32];


	printk(KERN_INFO "%s.%d:%s system_rev: 0x%X\n", __FILE__, __LINE__, __FUNCTION__, system_rev);

	switch(system_rev) {
	case LF2000_BOARD_LUCY:
	case LF2000_BOARD_LUCY_PP:
		p_io_pad = &io_pad_lucy;
		break;
		
	case LF2000_BOARD_RIO:
	case LF2000_BOARD_RIO_KND_800_480:
		p_io_pad = &io_pad_rio;
		break;

	case LF2000_BOARD_RIO_BETA_1024_600:
	case LF2000_BOARD_RIO_BETA_800_480:
	case LF2000_BOARD_RIO_BETA_1024_600_700_400:
	case LF2000_BOARD_RIO_BETA_800_480_700_400:
	case LF2000_BOARD_RIO_BETA_1024_600_550_275:
		p_io_pad = &io_pad_rio_beta;
		break;

	case LF2000_BOARD_RIO_EP_550_275:
	case LF2000_BOARD_RIO_EP_666_333:
	case LF2000_BOARD_RIO_EP_800_333:
	case LF2000_BOARD_RIO_EP_700_400:
	case LF2000_BOARD_RIO_EP_800_400:
	case LF2000_BOARD_RIO_FEP_800_327P67:
	case LF2000_BOARD_RIO_FEP_800_327P666:
		p_io_pad = &io_pad_rio_ep;
		break;

	case LF2000_BOARD_VALENCIA:
	case LF2000_BOARD_VALENCIA_EP:
	case LF2000_BOARD_VALENCIA_EP_8:
	case LF2000_BOARD_VALENCIA_FEP:
	case LF2000_BOARD_VALENCIA_FEP_8:
	case LF2000_BOARD_VALENCIA_EP_800_480:
	case LF2000_BOARD_VALENCIA_EP_800_480_8:
	case LF2000_BOARD_VALENCIA_FEP_800_480:
	case LF2000_BOARD_VALENCIA_FEP_800_480_8:
	case LF2000_BOARD_VALENCIA_KND_800_480:
	case LF2000_BOARD_VALENCIA_KND_800_480_8:
	case LF2000_BOARD_VALENCIA_KND_1024_600:
	case LF2000_BOARD_VALENCIA_KND_1024_600_8:
		p_io_pad = &io_pad_val;
		break;

	case LF2000_BOARD_VALENCIA_CIP:
		p_io_pad = &io_pad_val_cip;
		break;

	case LF2000_BOARD_VTK:
		p_io_pad = &io_pad_vtk;
		break;

	default:
		p_io_pad = &io_pad_lucy;
		break;
	}

	/* GPIO pad function */
	for (io_grp = 0; NUMBER_OF_GPIO_MODULE > io_grp; io_grp++) {
		for (io_bit = 0; io_bit < 32; io_bit++) {
			if (! (*p_io_pad)[io_grp][io_bit])
				continue;

			io_mod = PAD_GET_PADMODE((*p_io_pad)[io_grp][io_bit]);

			switch(io_mod) {
			case PAD_MODE_IN:
				NX_GPIO_SetPadFunction (io_grp, io_bit, NX_GPIO_PADFUNC_GPIO);
				NX_GPIO_SetOutputEnable(io_grp, io_bit, CFALSE);
				break;
			case PAD_MODE_OUT:
				NX_GPIO_SetPadFunction (io_grp, io_bit, NX_GPIO_PADFUNC_GPIO);
				NX_GPIO_SetOutputEnable(io_grp, io_bit, CTRUE);
				break;
			case PAD_MODE_ALT1:
				NX_GPIO_SetPadFunction (io_grp, io_bit, NX_GPIO_PADFUNC_1);
				NX_GPIO_SetOutputEnable(io_grp, io_bit, CFALSE);
				break;
			case PAD_MODE_ALT2:
				NX_GPIO_SetPadFunction (io_grp, io_bit, NX_GPIO_PADFUNC_2);
				NX_GPIO_SetOutputEnable(io_grp, io_bit, CFALSE);
				break;
			case PAD_MODE_ALT3:
				NX_GPIO_SetPadFunction (io_grp, io_bit, NX_GPIO_PADFUNC_3);
				NX_GPIO_SetOutputEnable(io_grp, io_bit, CFALSE);
				break;
			case PAD_MODE_INT:
				detect = PAD_GET_DECTMODE((*p_io_pad)[io_grp][io_bit]);
				NX_GPIO_SetPadFunction(io_grp, io_bit, NX_GPIO_PADFUNC_GPIO);
				NX_GPIO_SetOutputEnable(io_grp, io_bit, CFALSE);
				NX_GPIO_SetInterruptMode(io_grp, io_bit, detect);
				break;
			case PAD_MODE_SKIP:
			case PAD_NOTEXIST:
			default:
				continue;
			}
			outval   = PAD_GET_OUTLEVEL((*p_io_pad)[io_grp][io_bit]);
			pullup   = PAD_GET_PULLUP((*p_io_pad)[io_grp][io_bit]);
			strength = PAD_GET_STRENGTH((*p_io_pad)[io_grp][io_bit]);

			NX_GPIO_SetOutputValue (io_grp, io_bit, (outval ? CTRUE : CFALSE));
			NX_GPIO_SetPullUpEnable(io_grp, io_bit, (pullup ? CTRUE : CFALSE));
			NX_CLKPWR_SetGPIOPadStrength(io_grp, io_bit, strength);
		}
	}
}

#define	ALVPADS	8

const U32 alv_pad_lucy[ALVPADS] = {
	PAD_GPIOALV0_LUCY, PAD_GPIOALV1_LUCY, PAD_GPIOALV2_LUCY, PAD_GPIOALV3_LUCY,
	PAD_GPIOALV4_LUCY, PAD_GPIOALV5_LUCY, PAD_GPIOALV6_LUCY, PAD_GPIOALV7_LUCY,
		};

const U32 alv_pad_rio[ALVPADS] = {
	PAD_GPIOALV0_RIO, PAD_GPIOALV1_RIO, PAD_GPIOALV2_RIO, PAD_GPIOALV3_RIO,
	PAD_GPIOALV4_RIO, PAD_GPIOALV5_RIO, PAD_GPIOALV6_RIO, PAD_GPIOALV7_RIO,
		};

const U32 alv_pad_rio_beta[ALVPADS] = {
	PAD_GPIOALV0_RIO_BETA, PAD_GPIOALV1_RIO_BETA, PAD_GPIOALV2_RIO_BETA, PAD_GPIOALV3_RIO_BETA,
	PAD_GPIOALV4_RIO_BETA, PAD_GPIOALV5_RIO_BETA, PAD_GPIOALV6_RIO_BETA, PAD_GPIOALV7_RIO_BETA,
		};

const U32 alv_pad_rio_ep[ALVPADS] = {
	PAD_GPIOALV0_RIO_EP, PAD_GPIOALV1_RIO_EP, PAD_GPIOALV2_RIO_EP, PAD_GPIOALV3_RIO_EP,
	PAD_GPIOALV4_RIO_EP, PAD_GPIOALV5_RIO_EP, PAD_GPIOALV6_RIO_EP, PAD_GPIOALV7_RIO_EP,
		};

const U32 alv_pad_val[ALVPADS] = {
	PAD_GPIOALV0_VAL, PAD_GPIOALV1_VAL, PAD_GPIOALV2_VAL, PAD_GPIOALV3_VAL,
	PAD_GPIOALV4_VAL, PAD_GPIOALV5_VAL, PAD_GPIOALV6_VAL, PAD_GPIOALV7_VAL,
		};

const U32 alv_pad_val_cip[ALVPADS] = {
	PAD_GPIOALV0_VAL_CIP, PAD_GPIOALV1_VAL_CIP, PAD_GPIOALV2_VAL_CIP, PAD_GPIOALV3_VAL_CIP,
	PAD_GPIOALV4_VAL_CIP, PAD_GPIOALV5_VAL_CIP, PAD_GPIOALV6_VAL_CIP, PAD_GPIOALV7_VAL_CIP,
		};

const U32 alv_pad_vtk[ALVPADS] = {
	PAD_GPIOALV0_VTK, PAD_GPIOALV1_VTK, PAD_GPIOALV2_VTK, PAD_GPIOALV3_VTK,
	PAD_GPIOALV4_VTK, PAD_GPIOALV5_VTK, PAD_GPIOALV6_VTK, PAD_GPIOALV7_VTK,
		};

static void init_alive_pad(void)
{
	int  io_bit, det_mod;
	U32  io_mod, outval, detect, pullup;

	const U32 (*p_alv_pad)[ALVPADS];

	switch(system_rev) {
	case LF2000_BOARD_LUCY:
	case LF2000_BOARD_LUCY_PP:
		p_alv_pad = &alv_pad_lucy;
		break;

	case LF2000_BOARD_RIO:
	case LF2000_BOARD_RIO_KND_800_480:
		p_alv_pad = &alv_pad_rio;
		break;
		
	case LF2000_BOARD_RIO_BETA_1024_600:
	case LF2000_BOARD_RIO_BETA_800_480:
	case LF2000_BOARD_RIO_BETA_1024_600_700_400:
	case LF2000_BOARD_RIO_BETA_800_480_700_400:
	case LF2000_BOARD_RIO_BETA_1024_600_550_275:
		p_alv_pad = &alv_pad_rio_beta;
		break;

	case LF2000_BOARD_RIO_EP_550_275:
	case LF2000_BOARD_RIO_EP_666_333:
	case LF2000_BOARD_RIO_EP_800_333:
	case LF2000_BOARD_RIO_EP_700_400:
	case LF2000_BOARD_RIO_EP_800_400:
	case LF2000_BOARD_RIO_FEP_800_327P67:
	case LF2000_BOARD_RIO_FEP_800_327P666:
		p_alv_pad = &alv_pad_rio_ep;
		break;

	case LF2000_BOARD_VALENCIA:
	case LF2000_BOARD_VALENCIA_EP:
	case LF2000_BOARD_VALENCIA_EP_8:
	case LF2000_BOARD_VALENCIA_FEP:
	case LF2000_BOARD_VALENCIA_FEP_8:
	case LF2000_BOARD_VALENCIA_EP_800_480:
	case LF2000_BOARD_VALENCIA_EP_800_480_8:
	case LF2000_BOARD_VALENCIA_FEP_800_480:
	case LF2000_BOARD_VALENCIA_FEP_800_480_8:
	case LF2000_BOARD_VALENCIA_KND_800_480:
	case LF2000_BOARD_VALENCIA_KND_800_480_8:
	case LF2000_BOARD_VALENCIA_KND_1024_600:
	case LF2000_BOARD_VALENCIA_KND_1024_600_8:
		p_alv_pad = &alv_pad_val;
		break;

	case LF2000_BOARD_VALENCIA_CIP:
		p_alv_pad = &alv_pad_val_cip;
		break;

	case LF2000_BOARD_VTK:
		p_alv_pad = &alv_pad_vtk;
		break;

	default:
		p_alv_pad = &alv_pad_lucy;
		break;
	}

	/* Alive pad function */
	for (io_bit = 0; io_bit< ALVPADS; io_bit++) {

		io_mod = PAD_GET_PADMODE((*p_alv_pad)[io_bit]);

		switch(io_mod) {
		case PAD_MODE_IN   :
		case PAD_MODE_DECT :
			NX_ALIVE_SetOutputEnable(io_bit, CFALSE);
			break;
		case PAD_MODE_OUT  :
			NX_ALIVE_SetOutputEnable(io_bit, CTRUE);
			break;
		default :
			DBGOUT("\n Unknown GPIO ALIVE Mode(0x%x)\n", io_mod);
			continue;
		}
		outval = PAD_GET_PADMODE((*p_alv_pad)[io_bit]);
		pullup = PAD_GET_PULLUP((*p_alv_pad)[io_bit]);
		detect = PAD_GET_DECTMODE((*p_alv_pad)[io_bit]);

		NX_ALIVE_SetOutputValue (io_bit, (outval ? CTRUE : CFALSE));
		NX_ALIVE_SetPullUpEnable(io_bit, (pullup ? CTRUE : CFALSE));

		// set detect mode
		for (det_mod = 0; 6 > det_mod; det_mod++) {
			if (io_mod == PAD_MODE_DECT)
				NX_ALIVE_SetDetectMode(det_mod, io_bit, (det_mod == detect ? CTRUE : CFALSE));
			else
				NX_ALIVE_SetDetectMode(det_mod, io_bit, CFALSE);
		}
		NX_ALIVE_SetDetectEnable(io_bit, (io_mod == PAD_MODE_DECT ? CTRUE : CFALSE));
	}
}

#define BUSNUM	6
const U32 bus_pad_lucy[BUSNUM] = {
	PAD_BUS_STATIC_CNTL_LUCY, PAD_BUS_STATIC_ADDR_LUCY,  PAD_BUS_STATIC_DATA_LUCY,
	PAD_BUS_VSYNC_LUCY, PAD_BUS_HSYNC_LUCY, PAD_BUS_DE_LUCY
};

const U32 bus_pad_val[BUSNUM] = {
	PAD_BUS_STATIC_CNTL_VAL, PAD_BUS_STATIC_ADDR_VAL,  PAD_BUS_STATIC_DATA_VAL,
	PAD_BUS_VSYNC_VAL, PAD_BUS_HSYNC_VAL, PAD_BUS_DE_VAL
};

const U32 bus_pad_rio[BUSNUM] = {
	PAD_BUS_STATIC_CNTL_RIO, PAD_BUS_STATIC_ADDR_RIO,  PAD_BUS_STATIC_DATA_RIO,
	PAD_BUS_VSYNC_RIO, PAD_BUS_HSYNC_RIO, PAD_BUS_DE_RIO
};

const U32 bus_pad_rio_beta[BUSNUM] = {
	PAD_BUS_STATIC_CNTL_RIO_BETA, PAD_BUS_STATIC_ADDR_RIO_BETA,  PAD_BUS_STATIC_DATA_RIO_BETA,
	PAD_BUS_VSYNC_RIO_BETA, PAD_BUS_HSYNC_RIO_BETA, PAD_BUS_DE_RIO_BETA
};

const U32 bus_pad_rio_ep[BUSNUM] = {
	PAD_BUS_STATIC_CNTL_RIO_EP, PAD_BUS_STATIC_ADDR_RIO_EP,  PAD_BUS_STATIC_DATA_RIO_EP,
	PAD_BUS_VSYNC_RIO_EP, PAD_BUS_HSYNC_RIO_EP, PAD_BUS_DE_RIO_EP
};

const U32 bus_pad_val_cip[BUSNUM] = {
	PAD_BUS_STATIC_CNTL_VAL_CIP, PAD_BUS_STATIC_ADDR_VAL_CIP,  PAD_BUS_STATIC_DATA_VAL_CIP,
	PAD_BUS_VSYNC_VAL_CIP, PAD_BUS_HSYNC_VAL_CIP, PAD_BUS_DE_VAL_CIP
};

const U32 bus_pad_vtk[BUSNUM] = {
	PAD_BUS_STATIC_CNTL_VTK, PAD_BUS_STATIC_ADDR_VTK,  PAD_BUS_STATIC_DATA_VTK,
	PAD_BUS_VSYNC_VTK, PAD_BUS_HSYNC_VTK, PAD_BUS_DE_VTK
};

static void init_bus_pad(void)
{
	int  io_bit;
	U32  strength, buspad;

	const U32  (*p_bus_pad)[BUSNUM];

	switch(system_rev) {
	case LF2000_BOARD_LUCY:
	case LF2000_BOARD_LUCY_PP:
		p_bus_pad = &bus_pad_lucy;
		break;

	case LF2000_BOARD_RIO:
	case LF2000_BOARD_RIO_KND_800_480:
		p_bus_pad = &bus_pad_rio;
		break;
		
	case LF2000_BOARD_RIO_BETA_1024_600:
	case LF2000_BOARD_RIO_BETA_800_480:
	case LF2000_BOARD_RIO_BETA_1024_600_700_400:
	case LF2000_BOARD_RIO_BETA_800_480_700_400:
	case LF2000_BOARD_RIO_BETA_1024_600_550_275:
		p_bus_pad = &bus_pad_rio_beta;
		break;

	case LF2000_BOARD_RIO_EP_550_275:
	case LF2000_BOARD_RIO_EP_666_333:
	case LF2000_BOARD_RIO_EP_800_333:
	case LF2000_BOARD_RIO_EP_700_400:
	case LF2000_BOARD_RIO_EP_800_400:
	case LF2000_BOARD_RIO_FEP_800_327P67:
	case LF2000_BOARD_RIO_FEP_800_327P666:
		p_bus_pad = &bus_pad_rio_ep;
		break;

	case LF2000_BOARD_VALENCIA:
	case LF2000_BOARD_VALENCIA_EP:
	case LF2000_BOARD_VALENCIA_EP_8:
	case LF2000_BOARD_VALENCIA_FEP:
	case LF2000_BOARD_VALENCIA_FEP_8:
	case LF2000_BOARD_VALENCIA_EP_800_480:
	case LF2000_BOARD_VALENCIA_EP_800_480_8:
	case LF2000_BOARD_VALENCIA_FEP_800_480:
	case LF2000_BOARD_VALENCIA_FEP_800_480_8:
	case LF2000_BOARD_VALENCIA_KND_800_480:
	case LF2000_BOARD_VALENCIA_KND_800_480_8:
	case LF2000_BOARD_VALENCIA_KND_1024_600:
	case LF2000_BOARD_VALENCIA_KND_1024_600_8:
		p_bus_pad = &bus_pad_val;
		break;

	case LF2000_BOARD_VALENCIA_CIP:
		p_bus_pad = &bus_pad_val_cip;
		break;

	case LF2000_BOARD_VTK:
		p_bus_pad = &bus_pad_vtk;
		break;

	default:
		p_bus_pad = &bus_pad_lucy;
		break;
	}

	/* BUS pad function */
	for (io_bit = 0; io_bit < BUSNUM; io_bit++) {
		buspad   = PAD_GET_BUS((*p_bus_pad)[io_bit]);
		strength = PAD_GET_STRENGTH((*p_bus_pad)[io_bit]);
		NX_CLKPWR_SetBusPadStrength(buspad, strength);
	}
}

/*------------------------------------------------------------------------------
 * board interface
 */
void board_init(void)
{
	init_gpio_pad();
	init_alive_pad();
	init_bus_pad();

	DBGOUT("%s : done board initialize ...\n", CFG_SYS_BOARD_NAME);
}
